/**
 * Explicit Lucide imports so bundlers keep these icons (dynamic `import *` lookups are tree-shaken).
 * Extend this map when new icon names are stored in the DB.
 */
import type { LucideIcon } from 'lucide-react'
import {
  AlertTriangle,
  Archive,
  Bike,
  BookOpen,
  Camera,
  Car,
  CircleCheck,
  Clock,
  Droplet,
  Dumbbell,
  FileText,
  Home,
  HousePlug,
  Key,
  KeyRound,
  Lightbulb,
  LogOut,
  Mail,
  MapPin,
  Package,
  QrCode,
  Search,
  Phone,
  Smartphone,
  Shirt,
  Sofa,
  Sparkles,
  Trash2,
  Tv,
  Users,
  Music2,
  WashingMachine,
  Wifi,
  Wine,
} from 'lucide-react'

export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
  BookOpen,
  Wifi,
  Key,
  KeyRound,
  Car,
  Trash2,
  Sparkles,
  AlertTriangle,
  Bike,
  Dumbbell,
  Home,
  Shirt,
  Users,
  MapPin,
  Phone,
  Mail,
  Smartphone,
  Search,
  QrCode,
  Camera,
  Music2,
  Clock,
  Package,
  Lightbulb,
  WashingMachine,
  Archive,
  LogOut,
  CircleCheck,
  HousePlug,
  FileText,
  Wine,
  Droplet,
  Sofa,
  Tv,
  /** Legacy name used in some mock data */
  CheckCircle2: CircleCheck,
  Spotify: Music2,
}

/** Icon names shown in the admin category picker (subset of {@link LUCIDE_ICON_MAP}). */
export const ADMIN_CATEGORY_ICON_OPTIONS = [
  'BookOpen',
  'Wifi',
  'Key',
  'KeyRound',
  'Car',
  'Trash2',
  'Sparkles',
  'AlertTriangle',
  'Bike',
  'Dumbbell',
  'Home',
  'Shirt',
  'Users',
  'MapPin',
  'Phone',
  'Mail',
  'Smartphone',
  'Search',
  'QrCode',
  'Camera',
  'Spotify',
  'Clock',
  'Package',
  'Lightbulb',
  'WashingMachine',
  'Archive',
  'LogOut',
  'CircleCheck',
  'HousePlug',
] as const

export type AdminCategoryIconName = (typeof ADMIN_CATEGORY_ICON_OPTIONS)[number]
